#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] || [ "$1" = "upgrade" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop hydrogenhttpd.service >/dev/null 2>&1 || true
    fi
fi

exit 0
